import type { CanonicalIconName } from './iconPaths';

export const ICON_ALIASES = {
  ac_unit: 'snow',
  add: 'plus',
  analytics: 'chart',
  anchor: 'map',
  arrow_forward: 'arrow',
  arrow_right_alt: 'arrow',
  assignment_ind: 'user',
  assignment_turned_in: 'check_circle',
  bar_chart: 'chart',
  bolt: 'bolt',
  business: 'briefcase',
  calendar_today: 'calendar',
  call: 'phone',
  category: 'grid',
  chat: 'chat',
  check: 'check',
  check_circle: 'check_circle',
  chevron_right: 'chevron_right',
  cleaning_services: 'tool',
  close: 'close',
  construction: 'tool',
  conveyor_belt: 'box',
  currency_exchange: 'coin',
  dashboard: 'grid',
  dashboard_customize: 'grid',
  description: 'doc',
  download: 'download',
  eco: 'leaf',
  edit: 'doc',
  edgesensor_low: 'target',
  emergency: 'support',
  engineering: 'tool',
  expand_more: 'chevron_down',
  fact_check: 'check_circle',
  factory: 'factory',
  farsight_digital: 'chart',
  filter_list: 'filter',
  flag: 'flag',
  flash_on: 'bolt',
  format_paragraph: 'paragraph',
  gavel: 'gavel',
  grid_view: 'grid',
  groups: 'users',
  handshake: 'hand',
  handyman: 'tool',
  headset_mic: 'support',
  horizontal_rule: 'minus',
  hub: 'share',
  info: 'info',
  integration_instructions: 'link',
  inventory: 'box',
  inventory_2: 'box',
  lan: 'link',
  language: 'globe',
  lightbulb: 'bulb',
  local_shipping: 'truck',
  location_on: 'pin',
  mail: 'mail',
  map: 'map',
  menu: 'menu',
  monitoring: 'chart',
  my_location: 'target',
  notifications_active: 'bell',
  pan_tool_alt: 'hand',
  payments: 'coin',
  person: 'user',
  phone: 'phone',
  phone_in_talk: 'phone',
  picture_as_pdf: 'doc',
  precision_manufacturing: 'tool',
  public: 'globe',
  query_stats: 'chart',
  radar: 'target',
  remove: 'minus',
  rocket_launch: 'rocket',
  satellite_alt: 'target',
  savings: 'coin',
  schedule: 'timer',
  search: 'search',
  security: 'shield',
  send: 'send',
  sensors: 'target',
  settings_input_component: 'settings',
  settings_suggest: 'settings',
  share: 'share',
  shield: 'shield',
  shield_lock: 'shield',
  shield_with_heart: 'shield',
  speed: 'target',
  star: 'star',
  straighten: 'map',
  support_agent: 'support',
  swap_horiz: 'arrow',
  target: 'target',
  thermostat: 'thermo',
  timer: 'timer',
  track_changes: 'target',
  train: 'train',
  translate: 'globe',
  trending_down: 'chart_down',
  trending_up: 'chart_up',
  verified: 'check_circle',
  verified_user: 'shield',
  visibility: 'eye',
  warehouse: 'warehouse',
  work: 'briefcase',
  workspace_premium: 'award',
  weight: 'box'
} as const satisfies Record<string, CanonicalIconName>;

export type IconName = keyof typeof ICON_ALIASES;

export const resolveIcon = (name: string | null | undefined): CanonicalIconName => {
  if (!name) return 'fallback';
  const normalized = name.trim() as IconName;
  return ICON_ALIASES[normalized] ?? 'fallback';
};
