export { default as GlyphIcon } from './GlyphIcon.astro';
export { default as LocalShippingIcon } from './LocalShippingIcon.astro';
export { default as InventoryIcon } from './InventoryIcon.astro';
export { default as GlobeIcon } from './GlobeIcon.astro';
export { default as TrainIcon } from './TrainIcon.astro';
export { default as TrackingIcon } from './TrackingIcon.astro';
export { default as VerifiedUserIcon } from './VerifiedUserIcon.astro';
export { default as RocketLaunchIcon } from './RocketLaunchIcon.astro';
export { default as CheckCircleIcon } from './CheckCircleIcon.astro';
export { default as MenuIcon } from './MenuIcon.astro';
export { default as CloseIcon } from './CloseIcon.astro';
export { default as SearchIcon } from './SearchIcon.astro';
export { default as MailIcon } from './MailIcon.astro';
export { default as PhoneIcon } from './PhoneIcon.astro';
export { default as ArrowForwardIcon } from './ArrowForwardIcon.astro';
export { default as ChevronRightIcon } from './ChevronRightIcon.astro';
export { default as ChevronDownIcon } from './ChevronDownIcon.astro';

export { ICON_ALIASES, resolveIcon, type IconName } from './iconMap';
export { ICON_GLYPHS, type CanonicalIconName } from './iconPaths';
export type { IconComponentProps } from './types';
